services:
  - type: web
    name: minaprosig-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/minaprosig/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html